### ISSUE TITLE
client端的Config文件配置

### ISSUE THREAD

**Issue by garfieldchu** [Kjuly/iPokeMon#15]
请问如果需要在本机部署，client端的Config文件需要如何配置？

**Comment by Kjuly** [comment]
只要补全 Config 中空缺部分就行: https://github.com/Kjuly/iPokeMon/blob/dev/Pokemon/Config.m
本地默认使用： `http://localhost:8080` 地址访问服务器。

还有，服务器端数据默认情况下是空白的，你需要设置一些数据。你可以通过执行 [iPokeMon-Server/scripts/update_script.py](https://github.com/Kjuly/iPokeMon-Server/blob/dev/scripts/update_script.py) 来更新数据。

```
# RUN QUEUE
def run_queue():
    # Region
    #re = Region()
    #re.get_new_set('CN') # get new region set from DB
    #re.add_regions()     # add modified (|code|) region data to DB, it'll overwrite original key-value pair
    #re.clean_set('CN')   # clean new region set in DB

    # Wild Pokemon
    wpm = WPM()
    #wpm.output()
    wpm.update()
    #wpm.remove()
```

**Comment by garfieldchu** [comment]
已经顺利运行成功：

步骤：
1. 用git下载项目。
2. 把Libs目录中不存在的项目手动下载，下载KYCircleMenu时要选iPokeMon分支
$ cd PokeMon/Libs/KYCircleMenu
$ git checkout iPokeMon
3. 编译时候把AFURLConnectionOperation.m改成不使用ARC编译，就可以成功编译
4.下载服务端，安装redis，python
5.先启动redis，然后运行初始化服务端数据脚本
ipokemon-server-dev/scripts/update_script.py
6.修改服务端的配置文件，config.py
7.启动ipokemon-server-dev和iPokeMon-Resource-Server
8.修改client配置文件，修改方法如作者上面的回复
9.运行客户端
10.在应用中如果需要显示精灵图片，就需要在设置中加载资源文件，如果不需要则可免

在此再次谢谢Kjuly一直不断的帮忙

**Comment by Kjuly** [comment]
@garfieldchu +1 主要还是你自己努力 :)
