### ISSUE TITLE
请问一下，编译出现这个错误是什么回事

### ISSUE THREAD

**Issue by websrc** [Kjuly/iPokeMon#16]
/Users/iosforensic/Desktop/iPoke/Pokemon/Controllers/MainViewController.m:581:73: Use of undeclared identifier 'kKYCircleMenuStateExpand'
谢谢

**Comment by Kjuly** [comment]
检查下 [KYCircleMenu](https://github.com/Kjuly/KYCircleMenu) 库有没顺利加入并引用 :)

**Comment by Kjuly** [comment]
如果已经加入，再进入库检查分支是不是iPokeMon，如果不是就切换到iPokeMon：

```
$ cd PokeMon/Libs/KYCircleMenu
$ git co iPokeMon
```

**Comment by websrc** [comment]
非常感谢您的回复，我已经加入了KYCircleMenu对应的两个文件，但还是编译出现错误，另外您说的“git co iPokeMon” 这个是什么命令？操作的时候提示：

git: 'co' is not a git command.

请指教。

谢谢

---

------------------ 原始邮件 ------------------

 发件人: Kaijie Yu notifications@github.com;

 发送时间: 2013-02-20 17:04:34

 收件人: Kjuly/iPokeMon iPokeMon@noreply.github.com; 

 抄送: websrc websrc@139.com; 

 主题: Re: [iPokeMon] 请问一下，编译出现这个错误是什么回事 (#16)

如果已经加入，再进入库检查分支是不是iPokeMon，如果不是就切换到iPokeMon：

$ cd PokeMon/Libs/KYCircleMenu
$ git co iPokeMon

**Comment by Kjuly** [comment]
`co`也就是`checkout`，我做了别名映射，你可以：

```
$ git checkout iPokeMon
```

**Comment by websrc** [comment]
奇怪了，还是不行，能否请你把整个项目文件直接发给我？

**Comment by Kjuly** [comment]
这个是完整的，其它开发者有顺利运行的，你可以参考下wiki：

> https://github.com/Kjuly/iPokeMon/wiki/Configuration

**Comment by Kjuly** [comment]
对了，checkout后，把原先KYCircleMenu引用删掉，再重新加入引用

**Comment by websrc** [comment]
怎么$ git clone -b dev --recursive git://github.com/Kjuly/iPokeMon.git iPokeMon  没办法得到所有的libs，还是要一个个下载，再导入对吗，谢谢您的指教，我是个菜鸟，才开始学习的。
导入是不是用xcode 右键 add file 这个操作对吗

**Comment by websrc** [comment]
哈哈，还是太复杂了，我先不弄了，您能提供一个简单的做游戏的模板吗，首先是动画，然后显示登陆界面，登陆成功之后再显示有多个tab的 主界面，哈哈，我的qq15464331  websrc@139.com

**Comment by Kjuly** [comment]
```
$ git clone -b dev --recursive git://github.com/Kjuly/iPokeMon.git iPokeMon
```

根据你comment的时间，我猜你应该还没让它下载完。
抛弃之前的文件，新建立一个文件再将整个项目clone下来，完整clone时间有点长，请耐心等待。

---

你可以通过<kbd>shift</kbd>+<kbd>cmd</kbd>+<kbd>a</kbd>来添加库引用（Reference）到项目中。

---

你可以看看 [Cocos2D-iPhone](https://github.com/cocos2d/cocos2d-iphone)，里边有许多demo的。
其它网上也有许多开源游戏，你可以自己搜搜看。;)

最为初学者，这个项目确实不怎么适合... :p

**Comment by websrc** [comment]
非常感谢您的耐心指导，哈哈，佩服和敬仰ing

**Comment by Kjuly** [comment]
You're welcome ;)

**Comment by zzz6519003** [comment]
@Kjuly git co是啥命令。。。

**Comment by AlexRezit** [comment]
@zzz6519003 checkout 的 alias.

**Comment by Kjuly** [comment]
@zzz6519003 可以看下这个 http://note.kjuly.com/note/git-aliases/

**Comment by websrc** [comment]
Kjuly,有个事情想请教你，我想在cocos2d里面做个登陆页面，需要用到UITextField，这个使用的例子，你那能提供一个给我吗？谢谢，另外cocosbuilder里面好像也没办法实现可以输入数据。

**Comment by websrc** [comment]
我在一个cocos2d的项目里面随便新建一个xib或者storyboard文件，会出现编译错误，所以好像没办法使用xib文件，还请指教

**Comment by Kjuly** [comment]
@websrc 涉及界面设计，我用的是UIKit，所以对Cocos2D-iPhone里的相关界面不是特别了解。Cocos2D-iPhone里有自带的Sample，几乎每个元素都能涉及到，你可以看看 ;)

**Comment by twir** [comment]
“kKYCircleMenuStateExpand”, 在编译的时候没有找到，看了KYCircleMenu.h,没有发现kKYCircleMenuStateExpand的定义。所以才出编译错误，请更新最新的CircleMenu 源码。

**Comment by Kjuly** [comment]
@twir 需要切换`KYCircleMenu`库分支到`iPokeMon` :)

**Comment by twir** [comment]
我下载了KYCircleMenu ,并且将KYCircleMenu.h，和KYCircleMenu.m连入到iPokeMon,

在“MainViewController.m” 第580行的“kKYCircleMenuStateExpand”
// Implement the completion block
    completionBlock = ^(BOOL finished) {
      [self.centerMenuUtilityViewController updateButtonsLayoutForState:kKYCircleMenuStateExpand
                                                               animated:YES];
      isCenterMenuOpening_ = YES;
    };
当编译到这里
 出现 “Use of undeclared identifier 'kKYCircleMenuStateExpand”错误'
我有看了KYCircleMenu.h，和KYCircleMenu.m，没有找到kKYCircleMenuStateExpand的定义
因此我先将这行注释掉，并且再编译，就通过了，但是运行起来menu的位置不对，我估计和这行有关
我想github上的KYCircleMenu.h，和KYCircleMenu.m应该不是最新的

**Comment by Kjuly** [comment]
@twir `KYCircleMenu`默认branch是`dev`，你需要切换到`iPokeMon`分支:

```
$ cd path/to/KYCircleMenu
$ git checkout iPokeMon
```

**Comment by twir** [comment]
哦，我找到了，谢谢，Cheers

**Comment by Kjuly** [comment]
@twir :+1:
