### ISSUE TITLE
Getting "_OBJC_CLASS_$_DeviceBlockingViewController", referenced from:

### ISSUE THREAD

**Issue by RamkrishnaClarion** [Kjuly/iPokeMon#22]
I have added on the reference control and then build the application then I found issues which I had listed below.

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_DeviceBlockingViewController", referenced from:
      objc-class-ref in MainViewController.o
  "_kDeviceUIDKey", referenced from:
      -[TrainerController _keyForDeviceUID] in TrainerController.o
  "_kIAPCurrencyTier1", referenced from:
      -[PMPurchaseManager init] in PMPurchaseManager.o
  "_kIAPCurrencyTier2", referenced from:
      -[PMPurchaseManager init] in PMPurchaseManager.o
  "_kIAPCurrencyTier3", referenced from:
      -[PMPurchaseManager init] in PMPurchaseManager.o
  "_kOAuthClientIdentifier", referenced from:
      -[OAuthManager init] in OAuthManager.o
      -[ServerAPIClient initWithBaseURL:] in ServerAPIClient.o
      -[OAuthManager init] in OAuthManager.o
      -[ServerAPIClient initWithBaseURL:] in ServerAPIClient.o
  "_kOAuthGoogleClientID", referenced from:
      -[OAuthManager init] in OAuthManager.o
  "_kOAuthGoogleClientSecret", referenced from:
      -[OAuthManager init] in OAuthManager.o
  "_kOAuthGoogleKeychainItemName", referenced from:
      -[OAuthManager init] in OAuthManager.o
  "_kOAuthGoogleScope", referenced from:
      -[OAuthManager init] in OAuthManager.o
  "_kServerAPIRoot", referenced from:
      +[ServerAPI root] in ServerAPIClient.o
  "_kmGLFreeAll", referenced from:
      _ccGLInvalidateStateCache in ccGLStateCache.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please help me which setting I forgot it.

**Comment by Kjuly** [comment]
I think you've forgot to configure your configuration file: [Master/Config.m](https://github.com/Kjuly/iPokeMon/blob/dev/Master/Config.m).
And b.t.w, build master or dev branch.
Hope this helps.
