### ISSUE TITLE
Nonexistant submodule

### ISSUE THREAD

**Issue by dcvz** [Kjuly/iPokeMon#23]
KYUnlockCodeManager submodule can't be found anywhere..

**Comment by Kjuly** [comment]
Hey @dchavezlive , you can just remove the reference of this lib, this lib is not that important, it's just for activating a device of the game that's downloaded from App Store.
There're some algorithm & formulas in it. Cause I've not found a good way to encrypt it, so I just hide it. Hope you can understand. :)

**Comment by mattgi** [comment]
Cloning into 'Master/Libs/KYUnlockCodeManager'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:Kjuly/KYUnlockCodeManager.git' into submodule path 'Master/Libs/KYUnlockCodeManager' failed

This causes the cloning to stop, leaving you without other submodules (e.g SSZipArchive) on exit. Can you remove the dependency or advise how to get all of the submodules?

**Comment by Kjuly** [comment]
@mattgi well, actually it's a private lib. And glad to note you that I just open sourced it. It's useless for current project, just a legacy lib. But maybe interesting. :jack_o_lantern:
