### ISSUE TITLE
Cannot download the app on Iphone device

### ISSUE THREAD

**Issue by khanhtrannnn** [Kjuly/iPokeMon#30]
Hello there,
Is it still possible to download app now ? I tried to change region to US but cannot.
![image](https://user-images.githubusercontent.com/17595069/37324348-5bbe92d0-26cc-11e8-90b0-893b4ba6a227.png)

**Comment by Kjuly** [comment]
Sorry, it's not available on Store now. Btw., replied ur mail as well.
